#!/bin/bash

helpFunction()
{
   echo ""
   echo "Usage: $0 -b buildType -O opensslPath -B boostPath"
   echo -e "\t-b Build Type - \"Debug\" or \"Release\""
   echo -e "\t-O Path to the openSSL root directory"
   echo -e "\t-B Path to the Boost root directory"
   exit 1 # Exit script after printing help
}

while getopts "b:O:B:" opt
do
   case "$opt" in
      b ) buildType="$OPTARG" ;;
      O ) opensslPath="$OPTARG" ;;
      B ) boostPath="$OPTARG" ;;
      ? ) helpFunction ;; # Print helpFunction in case parameter is non-existent
   esac
done

# Print helpFunction in case parameters are empty
if [ -z "$buildType" ] || [ -z "$opensslPath" ] || [ -z "$boostPath" ]
then
   echo "Some or all of the parameters are empty";
   helpFunction
fi

packageDir=`pwd`

mkdir -p cmake-build-release
cd cmake-build-release/
cmake -j 4 \
      --target sophiatx_cli_wallet \
      -DCMAKE_BUILD_TYPE=$buildType \
      -DAPP_INSTALL_DIR=$packageDir/debian/sophiatx-cli-wallet/usr/bin/ \
      -DCONF_INSTALL_DIR=$packageDir/debian/sophiatx-cli-wallet/etc \
      -DBUILD_PIC=ON \
      -DOPENSSL_ROOT_DIR=$opensslPath \
      -DBOOST_ROOT=$boostPath \
      ../../../../
cd ../