#!/bin/bash

helpFunction()
{
   echo ""
   echo "Usage: $0 -n configDirName -b buildType -t testnet -G genesisPath -O opensslPath -B boostPath"
   echo -e "\t-n Config directory name. Configs will be created in /etc/${configDirName} "
   echo -e "\t-b Build Type - \"Debug\" or \"Release\""
   echo -e "\t-t Build SophiaTX as testnet - \"true\" or \"false\""
   echo -e "\t-G Path to the genesis file"
   echo -e "\t-O Path to the openSSL root directory"
   echo -e "\t-B Path to the Boost root directory"
   exit 1 # Exit script after printing help
}

while getopts "n:b:t:G:O:B:" opt
do
   case "$opt" in
      n ) configDirName="$OPTARG" ;;
      b ) buildType="$OPTARG" ;;
      t ) testnet="$OPTARG" ;;
      G ) genesisPath="$OPTARG" ;;
      O ) opensslPath="$OPTARG" ;;
      B ) boostPath="$OPTARG" ;;
      ? ) helpFunction ;; # Print helpFunction in case parameter is non-existent
   esac
done

# Print helpFunction in case parameters are empty
if [ -z "configDirName" ] [ -z "$buildType" ] || [ -z "$testnet" ] || [ -z "$genesisPath" ] || [ -z "$opensslPath" ] || [ -z "$boostPath" ]
then
   echo "Some or all of the parameters are empty";
   helpFunction
fi


# Creates directory for configs
configDir=../etc/$configDirName
mkdir -p $configDir/

# Copies default configs
cp ../../../contrib/fullnode_config.ini $configDir/config.ini

packageDir=`pwd`

mkdir -p cmake-build-release
cd cmake-build-release/
cmake -j 4 \
      --target sophiatxd_light \
      -DCMAKE_BUILD_TYPE=$buildType \
      -DBUILD_SOPHIATX_TESTNET=$testnet \
      -DSOPHIATX_EGENESIS_JSON=$genesisPath \
      -DBUILD_PIC=ON \
      -DOPENSSL_ROOT_DIR=$opensslPath \
      -DBOOST_ROOT=$boostPath \
      -DAPP_INSTALL_DIR=$packageDir/debian/sophiatx-light/usr/bin/ \
      -DCONF_INSTALL_DIR=$packageDir/debian/sophiatx-light/etc \
      -DSERVICE_INSTALL_DIR=$packageDir/debian/sophiatx-light/lib \
      ../../../../
cd ../