//                                   _           _    __ _ _        //
//                                  | |         | |  / _(_) |       //
//    __ _  ___ _ __   ___ _ __ __ _| |_ ___  __| | | |_ _| | ___   //
//   / _` |/ _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` | |  _| | |/ _ \  //
//  | (_| |  __/ | | |  __/ | | (_| | ||  __/ (_| | | | | | |  __/  //
//   \__, |\___|_| |_|\___|_|  \__,_|\__\___|\__,_| |_| |_|_|\___|  //
//    __/ |                                                         //
//   |___/                                                          //
//                                                                  //
// Generated by:  libraries/chain_id/identify_chain.cpp             //
//                                                                  //
// Warning: This is a generated file, any changes made here will be //
// overwritten by the build process.  If you need to change what    //
// is generated here, you should use the CMake variable             //
// GRAPHENE_EGENESIS_JSON to specify an embedded genesis state.     //
//                                                                  //

/*
 * Copyright (c) 2015, Cryptonomex, Inc.
 * All rights reserved.
 *
 * This source code is provided for evaluation in private test networks only, until September 8, 2015. After this date, this license expires and
 * the code may not be used, modified or distributed for any purpose. Redistribution and use in source and binary forms, with or without modification,
 * are permitted until September 8, 2015, provided that the following conditions are met:
 *
 * 1. The code and/or derivative works are used only for private test networks consisting of no more than 10 P2P nodes.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <sophiatx/protocol/types.hpp>
#include <sophiatx/egenesis/egenesis.hpp>

namespace sophiatx { namespace egenesis {

using namespace sophiatx::chain;

static const char genesis_json_array[122][40+1] =
{
"{\"initial_timestamp\":\"2018-04-11T14:05:4",
"0\",\"max_core_supply\":\"7319777577456890\",",
"\"initial_parameters\":{\"current_fees\":{\"p",
"arameters\":[[0,{\"fee\":100000}],[1,{\"basi",
"c_fee\":100000}],[2,{\"fee\":100000}],[3,{\"",
"basic_fee\":100000}],[4,{\"fee\":500000}],[",
"5,{\"fee\":10}],[6,{\"fee\":50000000}],[7,{\"",
"fee\":100000}],[8,{\"fee\":10}],[9,{\"fee\":1",
"00000,\"price_per_kbyte\":10}],[10,{\"fee\":",
"100000,\"price_per_kbyte\":10}],[11,{\"fee\"",
":100000}],[12,{\"fee\":100000}],[13,{\"fee\"",
":100000}],[14,{\"fee\":100000,\"price_per_k",
"byte\":10}],[15,{\"fee\":0}],[16,{\"fee\":100",
"000}],[17,{\"fee\":100000}],[18,{\"fee\":100",
"000,\"price_per_kbyte\":10}],[19,{\"fee\":10",
"00000}],[20,{\"fee\":1000000}],[21,{\"fee\":",
"0}],[22,{\"fee\":0}],[23,{\"fee\":0}],[24,{\"",
"fee\":0}],[25,{\"fee\":0}],[26,{\"fee\":0}],[",
"27,{\"fee\":0}],[28,{\"fee\":0}],[29,{\"fee\":",
"0}],[30,{\"fee\":0}],[31,{\"fee\":0}],[32,{\"",
"fee\":0}],[33,{\"fee\":500000}],[34,{\"fee\":",
"500000}],[35,{\"fee\":500000}],[36,{\"fee\":",
"500000}],[37,{\"fee\":500000}],[38,{\"fee\":",
"0}],[39,{\"fee\":100000}],[40,{\"fee\":0}],[",
"41,{\"fee\":0}],[42,{\"fee\":0}],[43,{\"fee\":",
"0}],[44,{\"fee\":0}],[45,{\"fee\":0}]],\"scal",
"e\":10000},\"block_interval\":5,\"maintenanc",
"e_interval\":86400,\"maintenance_skip_slot",
"s\":3,\"miner_proposal_review_period\":1209",
"600,\"maximum_transaction_size\":4096,\"max",
"imum_block_size\":4096000,\"maximum_time_u",
"ntil_expiration\":86400,\"maximum_proposal",
"_lifetime\":2419200,\"maximum_asset_feed_p",
"ublishers\":10,\"maximum_miner_count\":1001",
",\"maximum_authority_membership\":10,\"cash",
"back_vesting_period_seconds\":31536000,\"c",
"ashback_vesting_threshold\":\"10000000000\"",
",\"max_predicate_opcode\":1,\"max_authority",
"_depth\":2,\"extensions\":[]},\"initial_acco",
"unts\":[{\"name\":\"init0\",\"owner_key\":\"DCT8",
"2MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsb",
"uE1CpCwKy\",\"active_key\":\"DCT82MTCQVa9TDF",
"mz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"}",
",{\"name\":\"init1\",\"owner_key\":\"DCT82MTCQV",
"a9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpC",
"wKy\",\"active_key\":\"DCT82MTCQVa9TDFmz3Zwa",
"LzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"nam",
"e\":\"init2\",\"owner_key\":\"DCT82MTCQVa9TDFm",
"z3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\",\"",
"active_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAm",
"CLoJzrtFugpF72vsbuE1CpCwKy\"},{\"name\":\"in",
"it3\",\"owner_key\":\"DCT82MTCQVa9TDFmz3ZwaL",
"zsFAmCLoJzrtFugpF72vsbuE1CpCwKy\",\"active",
"_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzr",
"tFugpF72vsbuE1CpCwKy\"},{\"name\":\"init4\",\"",
"owner_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmC",
"LoJzrtFugpF72vsbuE1CpCwKy\",\"active_key\":",
"\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF",
"72vsbuE1CpCwKy\"},{\"name\":\"init5\",\"owner_",
"key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrt",
"FugpF72vsbuE1CpCwKy\",\"active_key\":\"DCT82",
"MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbu",
"E1CpCwKy\"},{\"name\":\"init6\",\"owner_key\":\"",
"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF7",
"2vsbuE1CpCwKy\",\"active_key\":\"DCT82MTCQVa",
"9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCw",
"Ky\"},{\"name\":\"init7\",\"owner_key\":\"DCT82M",
"TCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE",
"1CpCwKy\",\"active_key\":\"DCT82MTCQVa9TDFmz",
"3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{",
"\"name\":\"init8\",\"owner_key\":\"DCT82MTCQVa9",
"TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwK",
"y\",\"active_key\":\"DCT82MTCQVa9TDFmz3ZwaLz",
"sFAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"name\"",
":\"init9\",\"owner_key\":\"DCT82MTCQVa9TDFmz3",
"ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\",\"ac",
"tive_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCL",
"oJzrtFugpF72vsbuE1CpCwKy\"},{\"name\":\"init",
"10\",\"owner_key\":\"DCT82MTCQVa9TDFmz3ZwaLz",
"sFAmCLoJzrtFugpF72vsbuE1CpCwKy\",\"active_",
"key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrt",
"FugpF72vsbuE1CpCwKy\"},{\"name\":\"decent\",\"",
"owner_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmC",
"LoJzrtFugpF72vsbuE1CpCwKy\",\"active_key\":",
"\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF",
"72vsbuE1CpCwKy\"}],\"initial_assets\":[],\"i",
"nitial_active_miners\":11,\"initial_miner_",
"candidates\":[{\"owner_name\":\"init0\",\"bloc",
"k_signing_key\":\"DCT82MTCQVa9TDFmz3ZwaLzs",
"FAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"owner_",
"name\":\"init1\",\"block_signing_key\":\"DCT82",
"MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbu",
"E1CpCwKy\"},{\"owner_name\":\"init2\",\"block_",
"signing_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFA",
"mCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"owner_na",
"me\":\"init3\",\"block_signing_key\":\"DCT82MT",
"CQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1",
"CpCwKy\"},{\"owner_name\":\"init4\",\"block_si",
"gning_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmC",
"LoJzrtFugpF72vsbuE1CpCwKy\"},{\"owner_name",
"\":\"init5\",\"block_signing_key\":\"DCT82MTCQ",
"Va9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1Cp",
"CwKy\"},{\"owner_name\":\"init6\",\"block_sign",
"ing_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLo",
"JzrtFugpF72vsbuE1CpCwKy\"},{\"owner_name\":",
"\"init7\",\"block_signing_key\":\"DCT82MTCQVa",
"9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCw",
"Ky\"},{\"owner_name\":\"init8\",\"block_signin",
"g_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJz",
"rtFugpF72vsbuE1CpCwKy\"},{\"owner_name\":\"i",
"nit9\",\"block_signing_key\":\"DCT82MTCQVa9T",
"DFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy",
"\"},{\"owner_name\":\"init10\",\"block_signing",
"_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzr",
"tFugpF72vsbuE1CpCwKy\"}],\"initial_chain_i",
"d\":\"9a5e5be357cdfa2c48dbe260f983a0109b52",
"b9afdada705521cddad9243522f7\",\"initial_b",
"alances\":[{\"owner\":\"decent\",\"asset_symbo",
"l\":\"DCT\",\"amount\":\"5130608937456900\"}],\"",
"immutable_parameters\":{\"min_miner_count\"",
":11,\"num_special_accounts\":0,\"num_specia",
"l_assets\":0}}"
};

chain_id_type get_egenesis_chain_id()
{
   return chain_id_type( "aacab14d7b4c28dac6811fa71f1e71260919c3aa386352aaed4306652604b1de" );
}

void compute_egenesis_json( std::string& result )
{
   result.reserve( 4853 );
   result.resize(0);
   for( size_t i=0; i<122-1; i++ )
   {
      result.append( genesis_json_array[i], 40 );
   }
   result.append( std::string( genesis_json_array[ 122-1 ] ) );
   return;
}

fc::sha256 get_egenesis_json_hash()
{
   return fc::sha256( "aacab14d7b4c28dac6811fa71f1e71260919c3aa386352aaed4306652604b1de" );
}

} }
