#!/bin/sh
# postrm script for sophiatx-light

case "$1" in
    remove|purge)
        DATA_DIR=/var/lib/sophiatx_light
        LOG_DIR=/var/log/sophiatx_light

        rm -rf $DATA_DIR
        rm -rf $LOG_DIR
        rm -f /etc/default/sophiatx-light
    ;;

    *)
    ;;
esac

exit 0