/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AlexandriaJNI */

#ifndef _Included_AlexandriaJNI
#define _Included_AlexandriaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AlexandriaJNI
 * Method:    generateKeyPair
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_AlexandriaJNI_generateKeyPair
      (JNIEnv *, jobject);

/*
 * Class:     AlexandriaJNI
 * Method:    generateKeyPairFromBrainKey
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_AlexandriaJNI_generateKeyPairFromBrainKey
      (JNIEnv *, jobject, jstring);

/*
 * Class:     AlexandriaJNI
 * Method:    getPublicKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AlexandriaJNI_getPublicKey
      (JNIEnv *, jobject, jstring);

/*
 * Class:     AlexandriaJNI
 * Method:    getTransactionDigest
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AlexandriaJNI_getTransactionDigest
      (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     AlexandriaJNI
 * Method:    signDigest
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AlexandriaJNI_signDigest
      (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     AlexandriaJNI
 * Method:    addSignature
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AlexandriaJNI_addSignature
      (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     AlexandriaJNI
 * Method:    verifySignature
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_AlexandriaJNI_verifySignature
      (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     AlexandriaJNI
 * Method:    encryptMemo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AlexandriaJNI_encryptMemo
      (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     AlexandriaJNI
 * Method:    decryptedMemo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AlexandriaJNI_decryptedMemo
      (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
