#!/bin/sh
# postrm script for sophiatx

case "$1" in
    remove|purge)
        DATA_DIR=/var/lib/sophiatx
        LOG_DIR=/var/log/sophiatx

        rm -rf $DATA_DIR
        rm -rf $LOG_DIR
        rm -f /etc/default/sophiatx
    ;;

    *)
    ;;
esac

exit 0