#!/bin/sh

mkdir -p cmake-build-release
cd cmake-build-release/
cmake -j 4 \
      --target sophiatxd \
      -DCMAKE_BUILD_TYPE=$(CMAKE_BUILD_TYPE_ENV) \
      -DBUILD_SOPHIATX_TESTNET=$(BUILD_SOPHIATX_TESTNET_ENV) \
      -DSOPHIATX_EGENESIS_JSON=$(SOPHIATX_EGENESIS_JSON_ENV) \
      -DBUILD_PIC=ON \
      -DOPENSSL_ROOT_DIR=$(OPENSSL_ROOT_DIR_ENV) \
      -DBOOST_ROOT=$(BOOST_ROOT_DIR_ENV) \
      -DAPP_INSTALL_DIR=`pwd`/debian/sophiatx/usr/bin/ \
      -DCONF_INSTALL_DIR=`pwd`/debian/sophiatx/etc \
      -DSERVICE_INSTALL_DIR=`pwd`/debian/sophiatx/lib \
      ../../../../
cd ../